//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSAlyzer_v1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ipsalyzerContainer : DbContext
    {
        public ipsalyzerContainer()
            : base("name=ipsalyzerContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product_Func> Product_Func { get; set; }
        public virtual DbSet<Product_Cat> Product_Cat { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<recipe> recipes { get; set; }
        public virtual DbSet<Skin_Solution> Skin_Solution { get; set; }
    }
}
