//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSAlyzer_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int Product_FuncId { get; set; }
        public Nullable<int> Product_CatId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Pic_link { get; set; }
        public string Usage { get; set; }
        public string Usage_Pic { get; set; }
        public string Name_CN { get; set; }
        public string Description_CN { get; set; }
        public string Usage_CN { get; set; }
    
        public virtual Product_Func Product_Func { get; set; }
    }
}
